FROM vulnerables/web-dvwa:latest

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV WAZUH_MANAGER_IP=10.10.0.10
ENV WAZUH_AGENT_NAME=dvwa-server

RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list \
    && sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list \
    && sed -i '/stretch-updates/d' /etc/apt/sources.list \
    && apt-get update -o Acquire::Check-Valid-Until=false || true \
    && apt-get install -y --no-install-recommends -o Acquire::Check-Valid-Until=false \
        curl gnupg lsb-release ca-certificates apt-transport-https iproute2 iputils-ping || true

COPY ossec.conf /var/ossec/etc/ossec.conf

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]